CREATE TABLE IF NOT EXISTS `video` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(32) NOT NULL,
	`name` VARCHAR(256) NOT NULL,
	`url` VARCHAR(512) NOT NULL DEFAULT '',
	`section` INT(11) NOT NULL DEFAULT '0',
	`category` INT(11) NOT NULL DEFAULT '0',
	`pubdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `category` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL,
	`status` SMALLINT(4) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) 
);